spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        #nacos 的服务地址，nacos 的IP地址跟端口
        server-addr: 127.0.0.1:8848
server:
  servlet:
    context-path: /nacos-consumer

service-url:
  nacos-provider: http://nacos-provider

